import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const WTpaymentOrderModal = (props) => {
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "modal fade advance-btn-modal", id: "WT_Payment_OrdersModal", "data-backdrop": "static", tabIndex: "-1", role: "dialog", "aria-labelledby": "myLargeModalLabel", "aria-hidden": "true", children: _jsx("div", { className: "modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable", role: "document", children: _jsxs("div", { className: "modal-content w-50", style: { height: '80%', overflowY: 'auto', marginTop: '-145px' }, children: [_jsx("div", { className: "modal-header", children: _jsx("div", { className: "text-center", style: { width: '100%', color: 'white', backgroundColor: '#4235b4' }, children: "Select Tender Type" }) }), _jsx("div", { className: "modal-body pt-0", style: { display: 'flex', justifyContent: 'center' }, children: _jsxs("div", { className: "row", style: { width: '100px' }, children: [_jsx("button", { type: "button", className: "btn !bg-indigo-700 !text-white", 
                                            // onClick={() => UpdateStatusWTorders()}
                                            id: "btn_Payment_Modal_Close", "data-dismiss": "modal", children: "Cash" }), _jsx("button", { type: "button", className: "btn  !bg-indigo-700 !text-white", 
                                            // onClick={() => UpdateStatusWTorders()}
                                            id: "btn_Payment_Modal_Close", "data-dismiss": "modal", children: "Master Card" })] }) }), _jsxs("div", { className: "modal-footer border-top", style: { display: 'flex', justifyContent: 'center' }, children: [_jsx("button", { type: "button", className: "btn !bg-indigo-700 !text-white", id: "btn_Auto_AcceptTableModal_Close", "data-dismiss": "modal", children: "Cancel" }), _jsx("button", { type: "button", className: "btn !bg-indigo-700 !text-white", 
                                        // onClick={() => PaymentSubmitStatuseWTorders()}
                                        id: "btn_PaymentSubmitModal_Close", "data-dismiss": "modal", children: "Submit" })] })] }) }) }), _jsx("button", { type: "button", id: "btn_WT_Payment_OrdersModal", "data-toggle": "modal", "data-target": "#WT_Payment_OrdersModal", style: { display: "none" } })] }));
};
export default WTpaymentOrderModal;
