import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
const TaxModal = (props) => {
    const CloseCreateTax = () => {
        const button = document.getElementById('btnCancel_CreateTax_Modal_ManageSetting');
        if (button) {
            button.click();
        }
    };
    return (_jsxs(_Fragment, { children: [_jsx("button", { type: "button", id: "btn_CreateTax_Modal_ManageSoftwareSetting", "data-toggle": "modal", "data-target": "#ShowAddUpdateTaxModal_ManageSoftwareSetting", style: { display: "none" } }), _jsx("div", { className: "modal fade add-pay-modal", id: "ShowAddUpdateTaxModal_ManageSoftwareSetting", tabIndex: -1, role: "dialog", "aria-labelledby": "exampleModalCenterTitle", "aria-hidden": "true", children: _jsx("div", { className: "modal-dialog modal-dialog-centered", role: "document", children: _jsxs("div", { className: "modal-content", children: [_jsx("div", { className: "modal-header", children: _jsx("h5", { className: "modal-title", id: "heading_Title_TaxModal", children: "Create Tax" }) }), _jsx("div", { className: "modal-body", style: { height: "273px" }, children: _jsxs("form", { children: [_jsxs("div", { className: "form-group", children: [_jsx("label", { htmlFor: "textTaxName_ManageSoftwareSetting", children: "Name" }), _jsx("input", { type: "text", className: "form-control", id: "textTaxName_ManageSoftwareSetting", placeholder: "Enter tax name" }), _jsx("div", { className: "errorsClass2", id: "errorMsg_TaxName_ManageSoftwareSetting" })] }), _jsxs("div", { className: "form-group", children: [_jsx("label", { htmlFor: "textTaxRateValue_ManageSoftwareSetting", children: "Tax Rate (%)" }), _jsx("input", { type: "text", className: "form-control IsDecimal", id: "textTaxRateValue_ManageSoftwareSetting", placeholder: "0" }), _jsx("div", { className: "errorsClass2", id: "errorMsg_TaxRateValue_ManageSoftwareSetting" })] }), _jsxs("div", { className: "form-group", style: { display: "flex", flexDirection: "column" }, children: [_jsx("label", { htmlFor: "ddlTaxType_ManageSoftwareSetting", children: "Type" }), _jsxs("select", { id: "ddlTaxType_ManageSoftwareSetting", children: [_jsx("option", { value: "0", children: "Select option" }), _jsx("option", { value: "1", children: "Included in the price" }), _jsx("option", { value: "2", children: "Without included in the price" })] }), _jsx("div", { className: "errorsClass2", id: "error_ddlTaxType_ManageSoftwareSetting" })] })] }) }), _jsxs("div", { className: "modal-footer", children: [_jsx("button", { id: "btnCancel_CreateTax_Modal_ManageSetting", type: "button", className: "cstm_model_plusbtn_1 btn btn-danger", "data-dismiss": "modal", style: { display: "none" } }), _jsx("button", { type: "button", className: "btn add-pay", onClick: CloseCreateTax, children: "Cancel" }), _jsx("button", { id: "btnSubmit_Tax_ManageSetting", type: "button", className: "btn add-pay", onclick: "AddUpdateTax(1);", children: "Add" }), _jsx("button", { id: "btnUpdate_Tax_ManageSetting", type: "button", className: "btn add-pay", onclick: "AddUpdateTax(2);", style: { display: "none" }, children: "Update" })] })] }) }) })] }));
};
export default TaxModal;
