import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import PaymentModal from './PaymentModal';
const TendorPayment = () => {
    const OpenPaymentTenderTypeModal = () => {
        const button = document.getElementById('btn_PaymentTenderType_Modal_ManageSoftwareSetting');
        if (button) {
            button.click();
        }
    };
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "", id: "v-pills-tendor", role: "tabpanel", "aria-labelledby": "v-pills-tendor-tab", children: _jsxs("div", { className: "tab-set", children: [_jsx("button", { type: "button", className: "btn add-pay", onClick: OpenPaymentTenderTypeModal, children: "+ Add Payment Type" }), _jsx("button", { type: "button", className: "btn dalete-pay", onClick: "OpenDeletePaymentTenderType();", children: _jsx("i", { className: "fa fa-trash", "aria-hidden": "true" }) }), _jsxs("div", { className: "set-check-box tenderPaymentTypeSection ui-sortable", children: [_jsxs("div", { className: "form-check d-flex align-items-center TenderTypeSectionCommonClass ui-sortable-handle", "data-rid": "1", children: [_jsx("label", { className: "form-check-label flex-grow-1", children: "Cash" }), _jsx("div", { className: "toggle-btn me-4", children: _jsxs("label", { className: "switch", children: [_jsx("input", { type: "checkbox", className: "activeTenderTypeCommonClass", id: "toggleBtn_ActiveTenderType_ManageSoftwareSetting_1", onChange: "updateTenderTypeStatus(1);", checked: true }), _jsx("span", { className: "slider round" }), _jsx("i", { className: "input-helper" })] }) }), _jsx("i", { className: "fa fa-edit btn_tenderPaymentData", "data-id": "1", title: "Edit Tender Type", "aria-hidden": "true", id: "btn_tenderPaymentData1", style: { fontSize: "24px", cursor: "pointer" } })] }), _jsxs("div", { className: "form-check d-flex align-items-center TenderTypeSectionCommonClass ui-sortable-handle", "data-rid": "2", children: [_jsx("label", { className: "form-check-label flex-grow-1", children: "EFTPOS" }), _jsx("div", { className: "toggle-btn me-4", children: _jsxs("label", { className: "switch", children: [_jsx("input", { type: "checkbox", className: "activeTenderTypeCommonClass", id: "toggleBtn_ActiveTenderType_ManageSoftwareSetting_2", onChange: "updateTenderTypeStatus(2);", checked: true }), _jsx("span", { className: "slider round" }), _jsx("i", { className: "input-helper" })] }) }), _jsx("i", { className: "fa fa-edit btn_tenderPaymentData", "data-id": "3", title: "Edit Tender Type", "aria-hidden": "true", id: "btn_tenderPaymentData3", style: { fontSize: "24px", cursor: "pointer" } })] })] })] }) }), _jsx(PaymentModal, {})] }));
};
export default TendorPayment;
