import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import "./App.css";
import Layout from "./components/Layout/Layout";
import Dashboard from "./pages/ReastaurantPanel/Dashboard";
import ForgotPassword from "./pages/ForgotPassword";
import Login from "./pages/RestaurantLogin";
import ManageReasons from "./pages/ReastaurantPanel/ManageReasons";
import SoftwareSetting from "./pages/ReastaurantPanel/SoftwareSetting";
import ManageProfile from "./pages/ReastaurantPanel/ManageProfile";
import ManageReports from "./pages/ReastaurantPanel/ManageReports";
import StoreQR from "./components/ReastaurantPanel/peripherals/StoreQR";
import Stripesetup from "./components/ReastaurantPanel/peripherals/Stripesetup";
import TableQR from "./components/ReastaurantPanel/peripherals/TableQR";
import ManageProducts from "./pages/ReastaurantPanel/ManageProducts";
import MainDepartment from "./components/ReastaurantPanel/manageProducts/MainDepartment";
import AddDepartment from "./components/ReastaurantPanel/manageProducts/AddDepartment";
import AddPrintGroup from "./components/ReastaurantPanel/manageProducts/AddPrintGroup";
import AddProduct from "./components/ReastaurantPanel/manageProducts/AddProduct";
import MenuSetup from "./pages/ReastaurantPanel/MenuSetup";
import KIOSMenu from "./components/ReastaurantPanel/menusetup/KIOSMenu";
import POSmenu from "./components/ReastaurantPanel/menusetup/POSmenu";
import UpSellProduct from "./components/ReastaurantPanel/manageProducts/UpSellProduct";
import ImportProducts from "./components/ReastaurantPanel/manageProducts/ImportProducts";
import SpeedTool from "./components/ReastaurantPanel/manageProducts/SpeedTool";
import ComboProducts from "./components/ReastaurantPanel/manageProducts/ComboProducts";
import ManageOrders from "./components/ReastaurantPanel/peripherals/ManageOrders";
// import ManageProfile from "./pages/ReastaurantPanel/ManageProfile";
// import ManageReports from "./pages/ReastaurantPanel/MangeReports";
// import MenuSetup from "./pages/ReastaurantPanel/MenuSetup";
// import KIOSMenu from "./components/ReastaurantPanel/menusetup/KIOSMenu";
// import POSmenu from "./components/ReastaurantPanel/menusetup/POSmenu";
// import StoreQR from "./components/ReastaurantPanel/perpherals/StoreQR";
// import Stripesetup from "./components/ReastaurantPanel/perpherals/Stripesetup";
const App = () => {
    return (_jsx(BrowserRouter, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/forgot-password", element: _jsx(ForgotPassword, {}) }), _jsxs(Route, { path: "/", element: _jsx(Layout, {}), children: [_jsx(Route, { path: "/", element: _jsx(Dashboard, {}) }), _jsx(Route, { path: "/manage-profile", element: _jsx(ManageProfile, {}) }), _jsx(Route, { path: "/manage-reasons", element: _jsx(ManageReasons, {}) }), _jsx(Route, { path: "/manage-reports", element: _jsx(ManageReports, {}) }), _jsx(Route, { path: "/manage-products", element: _jsx(ManageProducts, {}) }), _jsx(Route, { path: "/manage-products/main-department", element: _jsx(MainDepartment, {}) }), _jsx(Route, { path: "/manage-products/add-department", element: _jsx(AddDepartment, {}) }), _jsx(Route, { path: "/manage-products/add-printGroup", element: _jsx(AddPrintGroup, {}) }), _jsx(Route, { path: "/manage-products/add-product", element: _jsx(AddProduct, {}) }), _jsx(Route, { path: "/manage-products/up-sell-product", element: _jsx(UpSellProduct, {}) }), _jsx(Route, { path: "/manage-products/import-products", element: _jsx(ImportProducts, {}) }), _jsx(Route, { path: "/manage-products/speed-tool", element: _jsx(SpeedTool, {}) }), _jsx(Route, { path: "/manage-products/combo-products", element: _jsx(ComboProducts, {}) }), _jsx(Route, { path: "/software-setting", element: _jsx(SoftwareSetting, {}) }), _jsx(Route, { path: "/menu-setup", element: _jsx(MenuSetup, {}) }), _jsx(Route, { path: "/kios-menu", element: _jsx(KIOSMenu, {}) }), _jsx(Route, { path: "/pos-menu", element: _jsx(POSmenu, {}) }), _jsx(Route, { path: "/store-Qr", element: _jsx(StoreQR, {}) }), _jsx(Route, { path: "/table-Qr", element: _jsx(TableQR, {}) }), _jsx(Route, { path: "/stripe-setup", element: _jsx(Stripesetup, {}) }), _jsx(Route, { path: "/manage-orders", element: _jsx(ManageOrders, {}) })] })] }) }));
};
export default App;
